### ISSUE TITLE
error in version 2.0.2 updater portable version

### ISSUE THREAD

**Issue by agokule** [username121546434/pit-mopper#7]
This is an auto generated bug report

## Description
I wanted to update pit mopper but this error popped up

## More information
Traceback: <traceback object at 0x000001E536D98F00>
Type: <class '_tkinter.TclError'>
Value: unknown option "-bg"

Full Traceback:
```
Traceback (most recent call last):
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\athar\Desktop\Python\pit-mopper\Scripts\updater.py", line 89, in check_for_updates
    timeout 3 /NOBREAK
            ~~^~~~~~~~~
  File "C:\Users\athar\Desktop\Python\pit-mopper\Scripts\functions.py", line 253, in change_theme_of_window
    break
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-bg"
```

<details>
  <summary>
    Debug Log Output
  </summary>
2024-05-27 21:59:17,237 [INFO]: Loading...

2024-05-27 21:59:17,368 [INFO]: Loading new app instance...
2024-05-27 21:59:17,504 [INFO]: Finished loading

</details>

**Comment by agokule** [comment]
I tested this in alpha code, this error didn't occur... I guess it magically fixed itself in the new code...
